### ISSUE TITLE
Pinterest scraper scrapes random selection of images instead of displayed board or search.

### ISSUE THREAD

**Issue by qool-naym** [maksimKorzh/one-time-scrapers#1]
Hey mate, first off - thanks for the really great tutorial on Youtube!
The script works perfectly fine there's one thing though I couldn't figure out yet:
I copied the html via your Web Grabber as instructed. But after having run the script, instead of downloading the images from my search term or a selected board it just downloads a bunch of random images instead (like architecture stuff, clothing, etc. literally everything but not what's displayed on the board or the search I grabbed the html from). 
Do you have any idea where the issue is or ideally how to fix this?
I manually copied a few of the image-links from the html to double check them right in the browser and they really aren't the same ones as those displayed on the screen (on either a board or a search).
Thanks in advance.

**Comment by maksimKorzh** [comment]
Hi @qool-naym 

I guess the source you're trying to grab within pinterest site is different compare to the one I used in my video - the board of a currently logged in user. I didn't test it with other sources.

Please send me a URL you're trying to grab and a screen show pointing out which images in particular you need to scrape, also please send me the HTML you've grabbed containing wrong images. I need to recreate the issue on my side first. I'll try to figure out what's going wrong there next. Finally I'll try to fix it and bring you the working solution.

please send your files to my email: freesoft.for.people@gmail.com
I don't promise a quick response with a solution - I'm extremely busy on my ongoing web scraping projects now.

**Comment by qool-naym** [comment]
Cool, thanks man! Will drop you an email tomorrow.
